name: flutter_audio_query
description: Flutter plugin to query data about artists, albums, songs, genres and playlists
  from device storage.
version: 1.0.0
#author: Marcos Antonio Boaventura <scavenger.gnu@gmail.com>
homepage: https://github.com/Gnac05/gnac_flutter_audio_query

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.16


flutter:
  plugin:
    platforms:
      android:
        package: boaventura.com.devel.br.flutteraudioquery
        pluginClass: FlutterAudioQueryPlugin